My location button
Sosol02/sdp pull request #108
Opened 2021-04-14 15:27 UTC by TheImpressiveDonut

2021-04-15 16:33 UTC, Ef55 requested changes
Only one issue: there are some Linter's warnings.
(Which I could not highlight for some reason).

2021-04-15 16:33 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/map/MapFragmentTest.java
> +    public void testMyLocationIsAppearing() {
Happy to know that I'm not the only one with this kind of problems.

2021-04-15 21:02 UTC, Ef55 approved these changes

2021-04-16 06:20 UTC, Sosol02 approved these changes

2021-04-16 06:20 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +        deviceLocationProvider = (DeviceLocationProvider) requireActivity();
I don't like the unconditionnal cast, but i don't know how you could have made it better

2021-04-16 06:44 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +        deviceLocationProvider = (DeviceLocationProvider) requireActivity();
We should be able to do better after PR #109

2021-04-16 07:47 UTC, merged