Calendar revamp
Sosol02/sdp pull request #111
Opened 2021-04-15 14:26 UTC by justagoodguy-omega

2021-04-15 16:55 UTC, TheImpressiveDonut requested changes
Would be nice if you could check the lint issue in single_cel_layout.xml and custom_calendar_view.xml

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/EventCreatorTest.java
> +//    }
If you want to ignore a test you can add @Ignore("string") under @Test. Instead of leaving commented code. Or just removed it.

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarFragment.java
>  import java.util.Objects;
There are 10 unused import, don't forget to use CTRL + SHIFT + O, not really important.

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarFragment.java
> +//        startActivity(intent);
Shouldn't we remove those commented code. hmmmmm

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +            }
empty for

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +    LayoutInflater inflater;
can be final, maybe put a private attribute

2021-04-15 16:55 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +//                popup.show(getChildFragmentManager(), getResources().getString(R.string.day_select_dialog_tag));
hmmm, this function does nothing, maybe remove commented part

2021-04-15 20:43 UTC, Ef55 approved these changes
The new calendar is really nice, but lacks a bit of polish (code-wise). I guess this PR just introduces the new calendar, so I think this is good enough.

Also, be wary of linter's warnings (but again, as I assume this is a preliminary version, this seems fine to me).

2021-04-15 20:43 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/CalendarUITest.java
> +    }
[Detail] This is already implemented in [helpers](https://github.com/Sosol02/sdp/blob/main/app/src/androidTest/java/com/github/onedirection/testhelpers/ViewChild.java) (yeah, I know it's auto-generated by Android-Studio).

2021-04-15 20:43 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +        inflater = LayoutInflater.from(context);
[Detail]
```suggestion
        this.inflater = LayoutInflater.from(context);
```
for consistency.
Also, it's easier to read if the attributes are initialized in the same order as they are declared, but not that we really need this here :)

2021-04-15 20:43 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +    private final List<Date> dates;
It seems to me that they could all be final.

2021-04-15 20:43 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +                final String year = yearFormat.format(dates.get(position));
What is the point of those three variables ? They don't seem to be used anywhere.

2021-04-15 20:43 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +    private CalendarGridAdapter calendarGridAdapter;
I think it would be clearer if you split the attributes in

- Attributes initialized at construction (i.e. here, at declaration site);
- Attributes initialized later in some initialization method.

Also, some attributes should be final (e.g. _yearFormat_). To go further: it seems to me that most of your attributes could be made final if you inlined _InitializeLayout_ in your constructor.

Also, I would personally always initialized all attributes at construction (even if it is to _null_) just to make clear that the attributes is voluntarily _null_ at build (but that's just my way of doing things).

2021-04-15 20:53 UTC, TheImpressiveDonut requested changes

2021-04-15 20:53 UTC, TheImpressiveDonut commented on app/src/main/res/layout/custom_calendar_view.xml
> +    android:id="@+id/activity_custom_calendar"
There are some hard coded string, it is better to put them in ressources, values.xml for instance

2021-04-16 06:27 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +                final String year = yearFormat.format(dates.get(position));
![image](https://user-images.githubusercontent.com/61226987/114980953-87bfbf80-9e8d-11eb-9a9d-30561bdbceab.png)

2021-04-16 06:39 UTC, justagoodguy-omega commented on app/src/main/res/layout/custom_calendar_view.xml
> +    android:id="@+id/activity_custom_calendar"
You are a horrible person Nico

2021-04-16 07:35 UTC, TheImpressiveDonut approved these changes

2021-04-16 07:36 UTC, merged