Sol notifications when event will happen
Sosol02/sdp pull request #113
Opened 2021-04-16 06:16 UTC by Sosol02

This is a draft PR to allow  you to see and comment but im not finished _at all_.

2021-05-03 18:40 UTC, Sosol02 commented
This PR f i n a l l y works but it still has a few TODOs to reslve (mostly via testing) and i want to refactor the schedule methode to take a ZonedDateTime. Otherwise, I also  need to add tests :) géantvidemourir

2021-05-04 14:15 UTC, Sosol02 commented
I did my best, plz review uwu

2021-05-04 16:06 UTC, Ef55 requested changes

2021-05-04 16:06 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/notification/NotificationPublisher.java
> +                    Log.d(LOG_TAG, "No event was available for scheduling the next call, " +
[Nitpick] It would be better to use [String::format](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)).

2021-05-04 16:06 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/notification/Notifications.java
> +        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
What happens if the version is not the expected one ?

2021-05-04 16:06 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/notification/Notifications.java
> +        // actually seems to not really matter for our usecase.
You should probably fix this (or at least use a TODO).

2021-05-04 16:07 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/EventsView.java
> +        //Notifications.getInstance(getApplicationContext()).scheduleEventNotifs(getApplicationContext(), eventHashSet);
you are right uwu

2021-05-04 16:09 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        Notifications.getInstance(getApplicationContext());
will do that

2021-05-04 16:10 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/notification/NotificationPublisher.java
> +    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
i keep that to make my purposes explict

2021-05-04 16:12 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/notification/NotificationPublisher.java
> +                    Log.d(LOG_TAG, "No event was available for scheduling the next call, " +
Yes but it is only for 1 element so i think it's ok

2021-05-04 16:13 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/notification/Notifications.java
> +        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
This is only necessary on modern android versions. Code taken straight from the documentation.

2021-05-04 16:14 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/notification/Notifications.java
> +        // actually seems to not really matter for our usecase.
This used to be a TODO but i checked the docs and the requestCode doesnt matter.

2021-05-04 16:39 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        Notifications.getInstance(getApplicationContext());
Actually the Android docs recommand not extending Application. The SO you linked dates from 2012.

2021-05-05 13:41 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        Notifications.getInstance(getApplicationContext());
Fair point, didn't realized when I found the post.
It seems we could use the [startup library](https://developer.android.com/reference/androidx/startup/package-summary) instead, but this goes out of the scope of this PR imo.

2021-05-05 13:43 UTC, Ef55 approved these changes
Lgtm

(thank's for setting *startup* up).

2021-05-05 14:50 UTC, hugolan approved these changes

2021-05-05 14:50 UTC, hugolan commented on app/src/main/java/com/github/onedirection/notification/Notifications.java
> +        String text =
maybe use stringbuilder

2021-05-06 11:18 UTC, merged