Recurring events revisited
Sosol02/sdp pull request #127
Opened 2021-04-18 22:00 UTC by Flechman

Revisited the way recurring events work and are stored.
There is now a specific model called "Recurring" which stores information about the recurrence of an event. Each event part of a recurrence series has a Recurring model and and has pointers to the previous event and the next event in the recurrence series.
This enables more freedom to the modification of any event whether it is recurring or not, + it keeps a better generalization of the event model in that generic operations on events do not have to distinguish between a recurring and a non-recurring event.

2021-04-19 19:45 UTC, justagoodguy-omega reviewed
So I'm just wondering now that you have this linked list implementation, if we give a specific day and month and year, how will you operate to find if one of these recurring events has an event on that day? Will you have to go through the whole list of every recurring event?

2021-04-19 19:45 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/events/Event.java
>      }
Is this constructor useful since the one underneath does the same but with Optional<Recurrence>? I mean if there is a version with Optional why is there a version without?

2021-04-19 20:36 UTC, Ef55 requested changes
The code is good but I'm a bit puzzled about the hows and whys.

There is at least missing documentation, and depending on it, some things might not be as practical as they should.

A good start to help me understand would be to answer:
"I want to create an event recurring every week for three weeks. How do I do that ?"

2021-04-19 20:36 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +public class Recurrence {
This should be serializable. 
In fact, I'm a bit worried by the fact that tests pass without this class being serializable...

2021-04-19 20:36 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    private Id nextEvent;
What do those attributs represent ?
Is groupId an Id for the whole "set" of events, or for the recurrence of this particular instance of the event ?
Are the other Ids the one of the instances, or of the recurrences linked to those Ids ?
What is this period ? The offset from the the time of the "initial" event, or the offset from the previous instance ?

2021-04-19 20:36 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    }
I'm not sure those are useful.
Also, what happens if there is already a next and I replace it ?
What once I store the event in the DB ?

2021-04-19 20:36 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    }
Why can we replace the ID ?
What's the point ? Won't it cause any issue with the DB ?

2021-04-19 21:44 UTC, Flechman commented
> So I'm just wondering now that you have this linked list implementation, if we give a specific day and month and year, how will you operate to find if one of these recurring events has an event on that day? Will you have to go through the whole list of every recurring event?

Since every event from the linked list is stored into the database, no additional work is needed. Just call the methods implemented in EventQueries

2021-04-19 21:48 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Event.java
>      }
Having one with Optional enables to pass null elements wrapped in the Optional (it is possible, ex. with a null location). Having another without  Optional enables to abstract away the Optional wrapper.

2021-04-19 21:48 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
Where do I say that ? It's false, they can be both null.

2021-04-19 21:50 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +public class Recurrence {
For the testing part, I implemented the testing of Recurrence in the exact same way as the testing for Event was made.

2021-04-20 06:35 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +public class Recurrence {
Yeah I realized afterwards that we never really test serialization, and since EventCreator doesn't use recurring events yet, the problem doesn't manifest itself.

2021-04-20 06:49 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
![image](https://user-images.githubusercontent.com/61226987/115350342-45f88700-a1b5-11eb-9766-5cf8fea40983.png)

2021-04-20 06:50 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/events/Event.java
>      }
![image](https://user-images.githubusercontent.com/61226987/115350287-35e0a780-a1b5-11eb-803a-d1d6cedea9ad.png)

2021-04-20 07:34 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
I guess that both might be null, but both cannot be null at the same time (if you see what I mean).

2021-04-20 08:25 UTC, justagoodguy-omega commented
> Since every event from the linked list is stored into the database, no additional work is needed. Just call the methods implemented in EventQueries

Sorry if I'm not understanding something but given that a recurring event can happen a potentially infinite number of times how can they all be in the database?

2021-04-20 10:01 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +public class Recurrence {
I'll nevertheless make it serializable

2021-04-20 10:02 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    }
You're right, this operation doesn't really fit with the purpose of the class Recurrence

2021-04-20 10:16 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
Sorry my explanations are not very clear. 
The Recurrence class is an object that is appended to an Event whenever this event belongs to a recurrence series, but it is not the recurrence series itself. 
The Recurrence object appended to an Event thus provides the information of this event in the recurrence series.
In the Recurrence object, we authorize the fact that both prev AND next can be null at the same time (without talking about recurrence series yet). This is useful for example when we want to create a recurrence series : upon creation of the recurrence series we base ourselves on an Event that is our reference for each Event  in our series. This Event has a Recurrence (R) appended to it to show that it IS a recurring event. But since the recurrence series has not been created yet, the pointers to other Event ids in the Recurrence (R) are null for the moment.
Now, the invariant applies to a recurrence series, i.e. to our linked list of Events that have Recurrence objects appended to them. The invariant says that the size of this linked list should not be less or equal to 1, i.e. there  should always be  at least 2 events in the linked-list. Upon creation of a recurrence series, if we see that the series will contain less than 2 events, then we don't create a recurrence series and we just create an ordinary Event (that doesn't have a Recurrence object  appended to it since it does not belong to a recurrence series).

2021-04-20 10:18 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
The recurrence series is defined and "recognized" with the attribute _groupId_ in Recurrence.

2021-04-20 10:33 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +        this(groupId, Duration.ofSeconds(periodSeconds), prev, next);
I see thanks! :)

2021-04-23 06:54 UTC, Ef55 reviewed
I still have one overall issue:
In my opinion, EventQueries should propose really high level methods, and I fell like there should be some methods whose only point is to check properties of an event and call appropriate functions, instead of having the user dissociate between all those cases.

I don't know if you feel this should be added in another PR, so I'm waiting for you opinion @Flechman

2021-04-23 06:54 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/EventQueries.java
> +    public CompletableFuture<Integer> addRecurringEvent(Event event) {
[Opinion] Imo, it would be nice to have a simpler wrapper around those two:
`
public CompletableFuture<Integer> addEvent(Event event) {
  if(event.isRecurrent()){
    addRecuringEvent(event);
  }
  else{
    addNonRecurringEvent(event);
  }
}
`
But I can add it myself in a future PR (if you don't see any issue to that).

2021-04-23 06:54 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/EventQueries.java
> +                    : db.store(new Event(e.getId(), event.getName(), event.getLocationName(), event.getCoordinates(), event.getStartTime(), event.getEndTime(), e.getRecurrence()));
[Opinion] I think that `changeRecurringSeriesEndTime` and `convertToRecurring` should be automatically called when 
`event.getRecurrent().endTime != e.getRecurrence().endTime`
or
`event.getRecurrent() != null && != e.getRecurrence() == null`
(this is not valid code, just conceptual ideas).

2021-04-23 07:48 UTC, Flechman commented on app/src/main/java/com/github/onedirection/EventQueries.java
> +    public CompletableFuture<Integer> addRecurringEvent(Event event) {
The problem is that both methods in the wrapper don't return the same type. But  this could be changed later if  this is really needed.

2021-04-23 08:06 UTC, Flechman commented on app/src/main/java/com/github/onedirection/EventQueries.java
> +                    : db.store(new Event(e.getId(), event.getName(), event.getLocationName(), event.getCoordinates(), event.getStartTime(), event.getEndTime(), e.getRecurrence()));
I think it's better for the moment to handle this on the programmer side as these methods are quite costly since they  query the database.

2021-04-23 08:07 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    private Id nextEvent;
I hope it's clearer now. We made a call so that I could explain to you the design.

2021-04-23 08:07 UTC, Flechman commented on app/src/main/java/com/github/onedirection/events/Recurrence.java
> +    }
After our call I hope this part is clearer as well now.

2021-04-23 08:11 UTC, Ef55 approved these changes

2021-04-23 08:19 UTC, justagoodguy-omega approved these changes

2021-04-23 08:40 UTC, merged