Calendar revamp with events
Sosol02/sdp pull request #129
Opened 2021-04-20 08:28 UTC by justagoodguy-omega

2021-04-22 16:22 UTC, TheImpressiveDonut requested changes

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/navigation/CalendarUITest.java
> +                .atPosition(15);
I think this doesn't test anything

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/navigation/TEMP.java
> +
I suppose the class name means it is temporary, shouldn't you delete it or maybe you want to keep it for later

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(nbOfEventsInDay + " Events");
There are some lints warning here

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/main/res/layout/day_select_popup.xml
> +        android:text="Add Event"
There is one lint warning here.

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/main/res/layout/day_select_popup.xml
> +        android:text="View Events"
There is one lint warning here.

2021-04-22 16:22 UTC, TheImpressiveDonut commented on app/src/main/res/layout/custom_calendar_view.xml
>      <LinearLayout
Would be nice if you could fix the lint warning in this file too if it can be done

2021-04-22 21:10 UTC, Sosol02 requested changes

2021-04-22 21:10 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +        //@TODO when the events list is implemented;
Consider throwing an UnsupportedOperationException to catch bugs if someone calls this function expecting it to be implemented.

2021-04-23 07:37 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/navigation/CalendarUITest.java
> +        Thread.sleep(20000);
do you need the Thread.sleep(20000)?

2021-04-23 07:37 UTC, hugolan commented on app/src/main/res/layout/custom_calendar_view.xml
> +            android:contentDescription="Our lord and savior dabbing to the right"
plz stop

2021-04-23 07:43 UTC, TheImpressiveDonut requested changes
Lint warnings !

2021-04-23 07:43 UTC, TheImpressiveDonut commented on app/src/main/res/layout/custom_calendar_view.xml
> +            android:contentDescription="Our lord and savior dabbing to the left"
There is a lint warning

2021-04-23 07:43 UTC, TheImpressiveDonut commented on app/src/main/res/layout/custom_calendar_view.xml
> +            android:contentDescription="Our lord and savior dabbing to the right"
There is a lint warning

2021-04-23 07:56 UTC, TheImpressiveDonut approved these changes
Nice !

2021-04-23 08:04 UTC, Sosol02 approved these changes

2021-04-23 08:05 UTC, merged