Implement cached geocoding
Sosol02/sdp pull request #142
Opened 2021-04-26 14:54 UTC by Ef55

2021-04-26 15:06 UTC, Sosol02 requested changes

2021-04-26 15:06 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +    private static class Key{
There may be a good reason but why not reuse utils.Pair?

2021-04-26 15:16 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +    private static class Key{
The reason is quite simple: I forgot its existence. 
Gonna fix it right now.

2021-04-26 15:32 UTC, Sosol02 approved these changes

2021-04-26 21:14 UTC, TheImpressiveDonut requested changes
One point to see, everything else looks good to me

2021-04-26 21:14 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> -
I'm not really sure how everything works, but I was wondering why did you remove this method here and instead made this method default in the interface GeoService?

2021-04-27 06:27 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> -
I'm gonna try (and probably fail to) make it quick:

1. getBestNamedCoordinates was first implemented;
2. getNamedCoordinates was later implemented; 
3. getBestNamedCoordinates could now be implemented in the interface using it;
4. While implementing the cache, I realized the previous point which would reduce the amount of code needed for every new geocoding service (including the cache), so here you are.

2021-04-28 14:50 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> -
Okya nice !

2021-04-28 14:54 UTC, TheImpressiveDonut approved these changes

2021-04-28 17:09 UTC, merged