Add a few features needed by the CachedDatabase to the Cache
Sosol02/sdp pull request #143
Opened 2021-04-26 21:02 UTC by Sosol02

Still needs a few tests to be added before merging, but you can still review the code.

2021-04-27 13:07 UTC, Flechman commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(k -> { throw new RuntimeException("Unreachable, get cache, k: " + k); }, maxHistory);
Should probably check that maxHistory is greater-eq than 0

2021-04-27 13:11 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(k -> { throw new RuntimeException("Unreachable, get cache, k: " + k); }, maxHistory);
It is already checked in the root constructor.

2021-04-27 13:15 UTC, Sosol02 commented
![atlas-coverage](https://user-images.githubusercontent.com/41057352/116247694-a316ae80-a75a-11eb-846d-9e8e852fcf82.jpeg)

2021-04-27 13:19 UTC, Ef55 requested changes
I think that you should at least add documentation to some of the most "non-trivial" (e.g. set/get functions) behaviors.
(+ the other points need to be addressed)

2021-04-27 13:19 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(getFunction, (k, v) -> { throw new RuntimeException("Unreachable, set cache, k: " + k + ", v: " + v); }, maxHistory);
Why "unreachable" ? The previous message seemed clearer.

2021-04-27 13:19 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(k -> { throw new RuntimeException("Unreachable, get cache, k: " + k); }, maxHistory);
No need; the called constructor already does this checked.

2021-04-27 13:19 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        //history.remove(key);
I think this should be enabled:
- If we have performance issues, we can always turn it back off;
- Not having it may lead (at least is seems so to me) to unexpected behaviors, which might be hard to track.

Eventually, there could be a boolean argument to specify the behavior.

2021-04-27 13:26 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        //history.remove(key);
I actually meant to remove that comment:
- The performance issues are not only issues but completely unacceptable since a going from O(1) to O(n) is simply not acceptable and in some way may defeat the purpose of having a cache.
- Using a boolean parameter seems to be a bad decision, it would mean leaking internal workings of the cache and make it more cubersome to implement the 2 alternatives at the same time while making sure no subtle bug happens.
- The behavior that you say may be "bad" or unexpected is very unlikely and the its only effect is to invalidate older entries a bit sooner than usual iff the cache is already full, and the effect doesnt last (once maxHistory elements are added no problem can ever ensue).
I will remove the comment and move my though process to the javadoc or something.

2021-04-27 13:27 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(getFunction, (k, v) -> { throw new RuntimeException("Unreachable, set cache, k: " + k + ", v: " + v); }, maxHistory);
Yeah, the meaning of these functions has changed, will document.
The get() and set() functions now have overloads to allow passing in a custom get/setFunction, which makes the ones passed by constructor the default ones.

2021-04-28 06:53 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(getFunction, (k, v) -> { throw new RuntimeException("Unreachable, set cache, k: " + k + ", v: " + v); }, maxHistory);
I stand by my comment; unreachable is seemingly not the word you are looking for, as if this is printed, this was clearly reached.

2021-04-28 08:10 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(getFunction, (k, v) -> { throw new RuntimeException("Unreachable, set cache, k: " + k + ", v: " + v); }, maxHistory);
It is written unreachable in the sense that this code should never have been called: if no default function is provided, it is an error to never provide a getFunction to get(k, f) and same for setFunction. "Unreachable" was more in the sense of "Should be unreachable but you reached it so you made a bad".
Also, 'Read only cache' was plain wrong since it is an intended use case to make caches with no default function and to provide one through get() and set() everytime, like in CachedDatabase, so you would end up with a cache that is not read only but with an error that would say so.
Maybe i should change it to "Should be unreachable" ? Or "No default get/setFunction provided" ?

2021-04-28 08:14 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +        this(getFunction, (k, v) -> { throw new RuntimeException("Unreachable, set cache, k: " + k + ", v: " + v); }, maxHistory);
I'm with you on the fact that the old message didn't match the current behavior.
Yeah, I think you should change it to something like that.

2021-04-28 08:17 UTC, Ef55 approved these changes

2021-04-28 09:03 UTC, Flechman approved these changes
Clean mechanism for the cache. I guess you could later do a new PR to finish the  documentation you started, it would make the code cleaner  and would further help in understanding how the cache works.

2021-04-28 09:23 UTC, merged