Implement a CachedDatabase to improve load times and responsivity of the app.
Sosol02/sdp pull request #144
Opened 2021-04-26 21:03 UTC by Sosol02

Still needs tests, but you can start reviewing anyways.
Blocked on #143, feel free to review it too.

2021-04-27 16:19 UTC, Sosol02 commented
I still need to write a few tests specific to the cache part of the database but it passes the tests in common with ConcreteDatabase.

2021-04-28 11:54 UTC, justagoodguy-omega approved these changes

2021-04-28 11:54 UTC, justagoodguy-omega commented on app/src/androidTest/java/com/github/onedirection/database/CommonDatabaseTests.java
> +    public static void canStoreAndRetrieveAndRemoveEvents(Database db) throws ExecutionException, InterruptedException {
Consider using foreach instead of indexing in the loops of these tests

2021-04-28 15:33 UTC, TheImpressiveDonut requested changes
Nice code !

2021-04-28 15:33 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/database/CachedDatabase.java
> +        return futId; */
Just checking if you forgot to remove this commented code or if you wanted to leave it.

2021-04-28 16:27 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/database/CachedDatabase.java
> +        return futId; */
Yep i'll delete that.

2021-04-28 16:28 UTC, Sosol02 commented on app/src/androidTest/java/com/github/onedirection/database/CommonDatabaseTests.java
> +    public static void canStoreAndRetrieveAndRemoveEvents(Database db) throws ExecutionException, InterruptedException {
Good call.

2021-04-28 16:36 UTC, TheImpressiveDonut approved these changes

2021-04-28 19:05 UTC, merged