Loading screen
Sosol02/sdp pull request #145
Opened 2021-04-27 08:14 UTC by justagoodguy-omega

2021-04-28 10:07 UTC, Ef55 requested changes
Happy to see that you learn from your past mistakes e13babf :)

2021-04-28 10:07 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +    private final Activity parentActivity = (Activity) this.getContext();
This doesn't look like a good idea.

2021-04-28 10:07 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +        Intent intent = new Intent(parentActivity, EventCreator.class);
You could simply use a [context](https://developer.android.com/reference/android/content/Intent?hl=en#Intent(android.content.Context,%20java.lang.Class%3C?%3E)), which would avoid the ugly cast mentioned before.

2021-04-28 10:07 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +        parentActivity.startActivity(intent);
Same here, the context should be enough.

2021-04-28 12:37 UTC, Sosol02 approved these changes
Looks okay.

2021-04-29 06:59 UTC, Ef55 requested changes
You also included some firebase-emulator configuration files, which should be removed.

2021-04-29 06:59 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +        LoadingDialog loadingDialog = new LoadingDialog((Activity) this.getContext());
Moving it doesn't make it better :)

2021-04-29 07:02 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/utils/LoadingDialog.java
> +        LayoutInflater inflater = activity.getLayoutInflater();
(Part of my previous review; dunno why github didn't include it)
You might use 
```suggestion
        LayoutInflater inflater = (LayoutInflater)context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
```
which would solve the aforementioned casting issue, as you did at [CustomCalendarView.java:111](https://github.com/Sosol02/sdp/blob/loadingScreen/app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java#L111).

2021-04-29 07:40 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CustomCalendarView.java
> +        LoadingDialog loadingDialog = new LoadingDialog((Activity) this.getContext());
Well here it literally asks for an activity :'(

2021-04-29 10:58 UTC, Ef55 approved these changes

2021-04-29 11:47 UTC, merged