Event viewer2
Sosol02/sdp pull request #157
Opened 2021-04-30 06:37 UTC by hugolan

2021-04-30 08:38 UTC, TheImpressiveDonut requested changes

2021-04-30 08:38 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/events/EventViewTest.java
>  import androidx.test.core.app.ApplicationProvider;
Is it normal there is a two test file named EventViewTest in different folder? Just wondering if you forgot to remove one

2021-04-30 08:38 UTC, TheImpressiveDonut commented on app/src/main/res/menu/activity_main_drawer.xml
> +            android:title="Your event list"/>
Hardcoded string

2021-04-30 08:43 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/events/EventViewTest.java
>  import androidx.test.core.app.ApplicationProvider;
yes

2021-04-30 08:50 UTC, Ef55 requested changes

2021-04-30 08:50 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/events/EventViewTest.java
> +            //onView(ViewMatchers.withId(R.id.textViewNameView)).check(matches(withText(EVENT.getName())));
This doesn't test anything; I think you should delete the whole file.

2021-04-30 08:50 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/navigation/NavigationActivityTest3.java
> +package com.github.onedirection.navigation;
Why do you have three testing files ?

2021-04-30 08:50 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/events/LocationsAdapter.java
> +            this.name = itemView.findViewById(R.id.eventName);
I don't know why you changed this.

2021-04-30 08:50 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(2021, 4, 1, 0, 0, 0, 0, ZoneId.systemDefault());
You should not hard-code this month date.

2021-04-30 08:50 UTC, Ef55 commented on app/src/main/res/layout/recyclerview_event_viewer_adapter.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
You have a lint warning here.

2021-04-30 09:43 UTC, TheImpressiveDonut requested changes

2021-04-30 09:43 UTC, TheImpressiveDonut commented on app/src/main/res/drawable/event_representation.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
Lint warning here, check if you can fix it.

2021-04-30 09:43 UTC, TheImpressiveDonut commented on app/src/main/res/layout/recyclerview_event_viewer_adapter.xml
> +    android:background="#FAFE"
lint warning here, not sure if fixable easily

2021-04-30 09:43 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/EventViewTest.java
> +            Thread.sleep(20000);
Look if you can change it, it would be nice. Use idlingRessource for instance

2021-05-04 08:42 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/EventViewTest.java
> +            Thread.sleep(20000);
paul didn't do it, I am not inclined to do it either

2021-05-04 08:49 UTC, hugolan commented on app/src/main/res/drawable/event_representation.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
yes it is because it didn't used it yet, but i will use it in the future

2021-05-05 11:01 UTC, justagoodguy-omega requested changes

2021-05-05 11:01 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +        eventViewerAdapter = new EventViewerAdapter(events);
Is it normal that this code may run before the Future right above it finishes and therefore before events is set to the right value?

2021-05-05 14:16 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +        eventViewerAdapter = new EventViewerAdapter(events);
change the code, this will not happen in the new implementation

2021-05-05 14:17 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +        ConcreteDatabase database = ConcreteDatabase.getDatabase();
change it in a way it do not use the db anymore

2021-05-05 14:18 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/EventViewTest.java
> +            Thread.sleep(20000);
made the change

2021-05-05 14:18 UTC, hugolan commented on app/src/main/res/layout/recyclerview_event_viewer_adapter.xml
> +    android:background="#FAFE"
fixed

2021-05-05 18:46 UTC, justagoodguy-omega approved these changes

2021-05-05 19:27 UTC, Ef55 requested changes
It's pretty good; there are just a few details to fix.

2021-05-05 19:27 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/events/EventCreatorTest.java
> +    public static class Wrapper<T> {
Why make this public ?
If there is any use to this, it should be moved into `testhelpers` (and maybe get a better name).

2021-05-05 19:27 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/events/EventViewTest.java
> +            //onView(ViewMatchers.withId(R.id.textViewNameView)).check(matches(withText(EVENT.getName())));
I stand by my previous point: this file is useless.
Also, you should move your other test file in the correct package (i.e. it should replace this one).

2021-05-05 19:27 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    }
[Nitpick]You could make it slightly more generic:
```suggestion
    public static Intent putEventListExtra(Intent intent, List<Event> eventList) {
        return intent.putExtra(EXTRA_LIST_EVENT, new ArrayList<>(eventList));
    }
```
Also, you should make the name coherent with the previous methods.

2021-05-05 19:27 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
I think this could be made into a local variable.

2021-05-05 19:27 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +                return false;
Is there any point in launching this activity without any events ?
(I guess this is gonna change in a future PR)

2021-05-05 19:32 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    }
good point

2021-05-05 19:34 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
I don't think maybe I'll need them for further development in other methods

2021-05-05 19:36 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
In this case, you might want to also update the attribute in the `updateResults` method.

2021-05-05 19:37 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +                return false;
yes for now, the events should be fetched from locally without passing by the db but to be made in a further pr

2021-05-05 19:42 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/events/EventViewTest.java
> +            //onView(ViewMatchers.withId(R.id.textViewNameView)).check(matches(withText(EVENT.getName())));
yeah this one is useless

2021-05-05 19:45 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
yeah I understand what you mean, but for the first time updating it consider it more as settings it rather than updating thats why I don't use the method

2021-05-05 19:48 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/events/EventCreatorTest.java
> +    public static class Wrapper<T> {
this auto generate by espresso

2021-05-05 19:50 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
I didn't express myself properly; I meant that you should most likely do something like
```
private void updateResults(List<Event> events){
    this.events = events;
    eventList.setAdapter(new EventViewerAdapter(events));
}
```
no that you should call `updateResults(...)` in the constructor.

2021-05-05 19:52 UTC, hugolan commented on app/src/main/java/com/github/onedirection/eventviewer/EventView.java
> +    List<Event> events = new ArrayList<Event>();
yeah ok that makes sense

2021-05-05 19:53 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/events/EventCreatorTest.java
> +    public static class Wrapper<T> {
I don't think so, unless espresso is my new nickname x)

2021-05-05 20:02 UTC, Ef55 approved these changes

2021-05-05 21:37 UTC, TheImpressiveDonut approved these changes
Nice

2021-05-05 21:44 UTC, merged