Fix NominatimGeocoding to follow guidelines
Sosol02/sdp pull request #197
Opened 2021-05-09 10:29 UTC by Ef55

Add mechanism to space requests by at least 1sec.
Add user-agent to requests.

2021-05-12 09:59 UTC, Sosol02 commented
How is the limit implemented? Does the returned future throw an exception, is it put into a queue? Just curious

2021-05-12 11:47 UTC, Flechman requested changes

2021-05-12 11:47 UTC, Flechman commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> +        long delay = Math.min(0, MIN_DELAY_MS - (SystemClock.uptimeMillis() - this.lastRequest));
Is it min or is it max ? I suppose that a delay can be positive (and is usually positive) so having either 0 or a negative value seems incorrect ?

2021-05-12 17:33 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> +        long delay = Math.min(0, MIN_DELAY_MS - (SystemClock.uptimeMillis() - this.lastRequest));
Nice catch ! This should be fixed now.
(`postDelayed` seemingly does this `max(0, ...)` operation itself).

2021-05-12 17:38 UTC, Ef55 commented
> How is the limit implemented? Does the returned future throw an exception, is it put into a queue? Just curious

In all honesty, I forgot to test what is the behavior of Nominatim in this case; It would most likely either return 50 results (so everything is fine except that you end up with less results than expected) or reject the request (in which case the future completes exceptionally).

2021-05-12 18:31 UTC, Flechman approved these changes

2021-05-13 12:37 UTC, Sosol02 requested changes

2021-05-13 12:37 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> +        long delay = Math.max(0, MIN_DELAY_MS - (SystemClock.uptimeMillis() - this.lastRequest));
You should store SystemClock.uptimeMillis in a variable and use it for here and line 140: the times may be different and the clock may not be monotonic.
I think it's not very important here but it's a good habit to have.

2021-05-13 12:43 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> +        long delay = Math.max(0, MIN_DELAY_MS - (SystemClock.uptimeMillis() - this.lastRequest));
In this particular case, this is intentional :)
The reason being that I want `lastRequest` to be after the handler was posted, in case there is some delay between the moment between the delay computation and the request posting.

2021-05-13 12:53 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/NominatimGeocoding.java
> +        long delay = Math.max(0, MIN_DELAY_MS - (SystemClock.uptimeMillis() - this.lastRequest));
oki

2021-05-13 12:54 UTC, Sosol02 approved these changes

2021-05-13 13:06 UTC, merged