Refactor default databases and add ObservableDatabase.
Sosol02/sdp pull request #199
Opened 2021-05-10 16:08 UTC by Sosol02

2021-05-10 16:17 UTC, Sosol02 commented
Still need to write tests but this pr is mostly refactoring and encapsulating so it should be allright.

2021-05-10 21:00 UTC, Flechman requested changes
You have mastered the CompletableFuture manipulation

2021-05-10 21:00 UTC, Flechman commented on app/src/main/java/com/github/onedirection/database/DefaultDatabase.java
> +public class DefaultDatabase {
What does this class do ? A small line to describe it could be nice

2021-05-10 21:00 UTC, Flechman commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +public class ObservableDatabase implements Database, Observable<ObservableDatabase.Action> {
Same small comment here

2021-05-10 21:00 UTC, Flechman commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +        observers.add(Objects.requireNonNull(observer));
Could directly `return observers.add(Objects.requireNonNull(observer));` instead of adding, and then just returning true.

2021-05-10 21:00 UTC, Flechman commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +        observers.add(Objects.requireNonNull(observer));
Same here

2021-05-10 21:00 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        }); // */
Can remove this I suppose (thankssss)

2021-05-10 21:03 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        }); // */
ok

2021-05-10 21:04 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +public class ObservableDatabase implements Database, Observable<ObservableDatabase.Action> {
Allows registering callbacks on database actions, will document.

2021-05-10 21:05 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +        observers.add(Objects.requireNonNull(observer));
only api i know where add returns a boolean xd, will do

2021-05-10 21:05 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/database/ObservableDatabase.java
> +        observers.add(Objects.requireNonNull(observer));
ssame

2021-05-10 21:30 UTC, Flechman approved these changes
Changes seem fine! AOK for me

2021-05-12 11:42 UTC, justagoodguy-omega approved these changes
Seems good to me

2021-05-12 11:45 UTC, merged