First version of the general theme of the UI + UI for the event creation
Sosol02/sdp pull request #202
Opened 2021-05-11 16:25 UTC by Flechman

Removed the Shreks in the calendar UI :((((

2021-05-12 07:36 UTC, justagoodguy-omega requested changes
The new UI looks great, I was just wondering if you could maybe also change the white square in the day_events_popup to something less blunt if possible?
![image](https://user-images.githubusercontent.com/61226987/117940450-61b10200-b309-11eb-9971-83d29c324541.png)

2021-05-12 07:36 UTC, justagoodguy-omega commented on app/src/main/res/layout/custom_calendar_view.xml
> -            />
![image](https://user-images.githubusercontent.com/61226987/117934214-bb61fe00-b302-11eb-9872-3ae47b0f52cb.png)

2021-05-12 07:36 UTC, justagoodguy-omega commented on app/src/main/res/layout/custom_calendar_view.xml
> -            />
![image](https://user-images.githubusercontent.com/61226987/117934821-58bd3200-b303-11eb-9426-c08160b19331.png)

2021-05-12 07:36 UTC, justagoodguy-omega commented on app/src/main/res/layout/day_select_popup.xml
> +        app:cornerRadius="50px" />
Use dp instead of px so that it adapts to screen densities

2021-05-12 07:36 UTC, justagoodguy-omega commented on app/src/main/res/layout/day_select_popup.xml
> +        app:cornerRadius="50px" />
Here too

2021-05-12 09:21 UTC, Flechman commented
> The new UI looks great, I was just wondering if you could maybe also change the white square in the day_events_popup to something less blunt if possible?
> ![image](https://user-images.githubusercontent.com/61226987/117940450-61b10200-b309-11eb-9971-83d29c324541.png)

I tried but until now I haven't found a solution :/ I'll keep on  looking but if you have an idea I'll take it.

2021-05-12 12:09 UTC, justagoodguy-omega commented
> 
> 
> > The new UI looks great, I was just wondering if you could maybe also change the white square in the day_events_popup to something less blunt if possible?
> > ![image](https://user-images.githubusercontent.com/61226987/117940450-61b10200-b309-11eb-9971-83d29c324541.png)
> 
> I tried but until now I haven't found a solution :/ I'll keep on looking but if you have an idea I'll take it.

Maybe something like this where the background is transparent? 
![image](https://user-images.githubusercontent.com/61226987/117972458-79997d80-b32b-11eb-8bdd-e4e9a5d1473a.png)
If you like it I just did it by adding this line:
`alertDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));`
In the CustomCalendarView like this:
`builder.setView(onDaySelectedPopup);
            alertDialog = builder.create();
            alertDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
            alertDialog.show();`

2021-05-12 12:19 UTC, Flechman commented
> > > The new UI looks great, I was just wondering if you could maybe also change the white square in the day_events_popup to something less blunt if possible?
> > > ![image](https://user-images.githubusercontent.com/61226987/117940450-61b10200-b309-11eb-9971-83d29c324541.png)
> > 
> > 
> > I tried but until now I haven't found a solution :/ I'll keep on looking but if you have an idea I'll take it.
> 
> Maybe something like this where the background is transparent?
> ![image](https://user-images.githubusercontent.com/61226987/117972458-79997d80-b32b-11eb-8bdd-e4e9a5d1473a.png)
> If you like it I commented in CustomCalendarView the line to add to make it look like this

Haha thanks that's exactly what I needed! I should've asked you before. I didn't think it would be in the java files that I had to change something

2021-05-12 15:55 UTC, TheImpressiveDonut requested changes
The ui is really nice. The changes are mainly xml files, so there nothing much to say. Just there quit some lint warnings, you could check if you can fix them. and another point shouldn't you remove the last item in this drawer (menu_event_viewer), I not sure if we need it anymore (it's sommething hugo added). 
![Screenshot from 2021-05-12 17-53-20](https://user-images.githubusercontent.com/61192980/118005806-fee05a80-b34a-11eb-9e82-45768f7e4e23.png)

2021-05-12 15:55 UTC, TheImpressiveDonut commented on app/src/main/res/layout/event_creator_geolocation_fragment.xml
> +            app:cornerRadius="50px" />
You should dp instead of px (Lint warning)

2021-05-12 15:55 UTC, TheImpressiveDonut commented on app/src/main/res/layout/event_creator_geolocation_fragment.xml
> +            app:cornerRadius="50px" />
You should dp instead of px (Lint warning)

2021-05-12 15:55 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_sign.xml
> +        app:cornerRadius="50px"
You should dp instead of px (Lint warning)

2021-05-12 15:55 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/event/EventViewTest.java
> -    public void testUiEventViewer() {
Is it normal that removed the test. Is it now obsolete with your changes?

2021-05-12 16:32 UTC, Flechman commented on app/src/androidTest/java/com/github/onedirection/event/EventViewTest.java
> -    public void testUiEventViewer() {
It is implemented in such a way that it is "sur-mesure" to the previous version of the UI. Now that the UI has changed, it doesn't work anymore. Hugo told me that I could delete it since it wasn't that useful anyway, and in any case he planned on deleting it later when he would make other changes.
PS: removing it doesn't reduce the coverage

2021-05-12 16:36 UTC, Flechman commented
> The ui is really nice. The changes are mainly xml files, so there nothing much to say. Just there quit some lint warnings, you could check if you can fix them. and another point shouldn't you remove the last item in this drawer (menu_event_viewer), I not sure if we need it anymore (it's sommething hugo added).
> ![Screenshot from 2021-05-12 17-53-20](https://user-images.githubusercontent.com/61192980/118005806-fee05a80-b34a-11eb-9e82-45768f7e4e23.png)

I'll put it as the home screen as we discussed last time. Having a list of upcoming events on the home screen seems nice.

2021-05-12 16:44 UTC, Flechman commented on app/src/main/res/layout/fragment_sign.xml
> +        app:cornerRadius="50px"
Will fix

2021-05-12 16:45 UTC, Flechman commented on app/src/main/res/layout/event_creator_geolocation_fragment.xml
> +            app:cornerRadius="50px" />
Will fix

2021-05-12 16:46 UTC, Flechman commented on app/src/main/res/layout/event_creator_geolocation_fragment.xml
> +            app:cornerRadius="50px" />
Will fix

2021-05-12 17:14 UTC, justagoodguy-omega commented
> 
> 
> > > > The new UI looks great, I was just wondering if you could maybe also change the white square in the day_events_popup to something less blunt if possible?
> > > > ![image](https://user-images.githubusercontent.com/61226987/117940450-61b10200-b309-11eb-9971-83d29c324541.png)
> > > 
> > > 
> > > I tried but until now I haven't found a solution :/ I'll keep on looking but if you have an idea I'll take it.
> > 
> > 
> > Maybe something like this where the background is transparent?
> > ![image](https://user-images.githubusercontent.com/61226987/117972458-79997d80-b32b-11eb-8bdd-e4e9a5d1473a.png)
> > If you like it I commented in CustomCalendarView the line to add to make it look like this
> 
> Haha thanks that's exactly what I needed! I should've asked you before. I didn't think it would be in the java files that I had to change something

No worries <3

2021-05-13 07:45 UTC, TheImpressiveDonut approved these changes

2021-05-13 10:05 UTC, justagoodguy-omega approved these changes

2021-05-13 10:16 UTC, merged