Minor calendar fix
Sosol02/sdp pull request #203
Opened 2021-05-11 17:14 UTC by justagoodguy-omega

2021-05-11 17:57 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Event", nbOfEventsInDay));
Format is not really needed here; you know that 
`nbOfEventsInDay == 1`.
Also, as requested in the coaches' review, such strings should be in strings.xml.

2021-05-12 09:55 UTC, Sosol02 requested changes
nice dock

2021-05-12 09:55 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/DayEventsListView.java
>          } else {
I think it would be cleaner if the function first checked for events.size() != 0, then inside it create and configure the alertDialog, instead of creating it and later dissmissing it.
Also (nitpick) you may want to Objects.requireNonNull(events) to avoid the NullPointerException.

2021-05-12 11:35 UTC, Sosol02 approved these changes

2021-05-12 17:42 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
This should also be in the strings.xml (sorry for not highlighting it earlier).

2021-05-13 08:09 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
I looked at it and I didn't see how to put it in string.xml since it needs nbOfEventsInDay as argument, are you sure it's possible?

2021-05-13 08:17 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
You should move the format string (`"%s Events"`) in _string.xml_, and do `String.format(R.string.event_count_format, nbOfEventsInDay)` on it.

2021-05-13 09:44 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
Yeah I'd tried to do that but it doesn't compile because String.format doesn't like R.string.event_count_format as argument

2021-05-13 09:52 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
From [here](http://www.envyandroid.com/android-string-xml-resource-formatting/), and with a bit of generalization:
```
String.format(view.getContext().getResources().getString(R.string.event_count_format), nbOfEventsInDay)
```
should work.

2021-05-13 10:06 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
cOde ReAdaBiLiTy

2021-05-13 10:14 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarGridAdapter.java
> +                        EventNumber.setText(String.format("%s Events", nbOfEventsInDay));
Fair point 🙃

2021-05-13 10:31 UTC, Ef55 approved these changes

2021-05-13 11:51 UTC, merged