added home to be event viewer
Sosol02/sdp pull request #212
Opened 2021-05-13 17:48 UTC by hugolan

home pull request

2021-05-13 20:56 UTC, Flechman requested changes

2021-05-13 20:56 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +public class HomeFragment extends Fragment implements  EventViewerAdapter.OnNoteListener{
You should document the class : what is its purpose ?

2021-05-13 20:56 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(2021, 5, 1, 0, 0, 0, 0, ZoneId.systemDefault());
Hardcoded values, + you should document why you chose these values. It would be better to have values that fit any date, and not only the current month during which you are making these changes.

2021-05-13 20:56 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
>  public class NavigationActivity extends AppCompatActivity {
You should add a documentation of the class, explaining the purpose

2021-05-13 20:56 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +    public CompletableFuture<List<Event>> getEventFromMonth(ZonedDateTime date) {
You could rewrite the method as a single line : 
```
return EventQueries.getEventsByMonth(Database.getDefaultInstance(), date);
```
If you use the method only once, it could be better to just replace the method call by the line.

2021-05-13 21:00 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(2021, 5, 1, 0, 0, 0, 0, ZoneId.systemDefault());
yep this just be deleted also

2021-05-13 21:00 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +public class HomeFragment extends Fragment implements  EventViewerAdapter.OnNoteListener{
ok

2021-05-13 21:01 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
>  public class NavigationActivity extends AppCompatActivity {
This class has been here since week 4 -_-

2021-05-13 21:01 UTC, Ef55 requested changes

2021-05-13 21:01 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(date.getYear(), date.getMonthValue(), 1, 0, 0, 0, 0, ZoneId.systemDefault());
Again, hard-coded date.

Also, why is this logic in both classes ?

2021-05-13 21:01 UTC, Ef55 commented on app/src/main/res/layout/activity_display_event.xml
> +    tools:context=".navigation.fragment.home.DisplayEvent">
All those strings shouldn't be hard-coded...

2021-05-13 21:01 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +    public CompletableFuture<List<Event>> getEventFromMonth(ZonedDateTime date) {
yes

2021-05-13 21:03 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/NavigationActivity.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(2021, 5, 1, 0, 0, 0, 0, ZoneId.systemDefault());
yes this was for testing

2021-05-13 21:04 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +        ZonedDateTime firstInstantOfMonth = ZonedDateTime.of(date.getYear(), date.getMonthValue(), 1, 0, 0, 0, 0, ZoneId.systemDefault());
testing

2021-05-13 21:04 UTC, hugolan commented on app/src/main/res/layout/activity_display_event.xml
> +    tools:context=".navigation.fragment.home.DisplayEvent">
yeah

2021-05-13 21:12 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/navigation/HomeTest.java
> +public class HomeTest {
yep

2021-05-13 21:16 UTC, hugolan commented
nice

2021-05-13 21:37 UTC, hugolan commented
i love sdp

2021-05-13 21:37 UTC, hugolan commented
> i love sdp

hahaha jokes on you

2021-05-13 21:47 UTC, Ef55 requested changes
The code now seems good, but the interface lacks a bit of polish in my opinion:
- I think you should add some margins around the list;
- The location names (which are long in case of full addresses) are not displayed properly. You might want to split the displayed address after the fist ','.

2021-05-14 07:16 UTC, Ef55 approved these changes

2021-05-14 07:33 UTC, Flechman approved these changes
In you next PRs you should improve the coverage and solve some UI issues such as putting a "go back" button once an event in the viewer is viewed.

2021-05-14 07:33 UTC, hugolan commented
home will display monthly events

2021-05-14 07:33 UTC, merged