Allow GeocodingCache dumping and integrate it in the app
Sosol02/sdp pull request #225
Opened 2021-05-15 15:07 UTC by Ef55

The cache is automatically loaded from file on app startup.
The cache is dumped every minute to file.

2021-05-15 16:50 UTC, Flechman requested changes
The code is very neat. I prefer that you review my single comment before I approve

2021-05-15 16:50 UTC, Flechman commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        Objects.requireNonNull(underlying);
Aren't you supposed to check this condition before anything you do in the  constructor ? I feel like it should be line 55.

2021-05-15 17:06 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        Objects.requireNonNull(underlying);
Not possible: when you call a constructor (from another constructor), it must be the first thing you do.

2021-05-15 20:09 UTC, Flechman commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        Objects.requireNonNull(underlying);
Ahhh yes I forgot the rule

2021-05-15 20:10 UTC, Flechman commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        Objects.requireNonNull(underlying);
Isn't it unsafe to call getNamedCoordinates then ?

2021-05-15 21:16 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        Objects.requireNonNull(underlying);
The method is called inside a lambda; said lambda is not called in the constructor, only later.
As such, this call to `Objects.requireNonNull(...)` should be sufficient.

2021-05-16 07:59 UTC, Flechman approved these changes

2021-05-17 09:16 UTC, TheImpressiveDonut requested changes
Nice code ! Just a few minor things to see.

2021-05-17 09:16 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +    public static Optional<GeocodingCache> loadFromAndroidCache(Context ctx, String filename, GeocodingService underlying) {
Since you tested if underlying is not null in the constructor, shouldn't you check it too in this method?

2021-05-17 09:16 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingService.java
> +class GeocodingServices {
Just wondering why is there a class in an interface?

2021-05-17 09:23 UTC, hugolan approved these changes

2021-05-17 09:23 UTC, hugolan commented on app/src/main/java/com/github/onedirection/utils/Cache.java
> +                            .collect(toMap(Map.Entry::getKey, Map.Entry::getValue))
[
![image](https://user-images.githubusercontent.com/61224371/118465139-e1700f80-b701-11eb-9943-0734af408e09.png)
](url)

nice code!

2021-05-17 09:23 UTC, hugolan commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        if(nameCache.isPresent() && coordinatesCache.isPresent()){
wouldn't it also work if only one of them is present in the android cache?

2021-05-17 10:02 UTC, Ef55 commented on app/src/main/AndroidManifest.xml
> +                android:name="com.github.onedirection.startup.ApplicationInitializer"
I renamed it because it is now also used to initialize the Geocoding default instance(s), so the previous name was a bit misleading.

2021-05-17 10:04 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingService.java
> +class GeocodingServices {
The class is not in (unless I messed up) in the interface but next to it. 
Java doesn't allow static attributes in interfaces, so I moved the code generating/storing the static instances into this package private class. The interface then retrieves the static fields and returns them as-if they were its own members.

2021-05-18 14:02 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/geolocation/geocoding/GeocodingCache.java
> +        if(nameCache.isPresent() && coordinatesCache.isPresent()){
Indeed; this case should never happen, so I didn't bother handling it in the most efficient way.
This could be an improvement but as said, it shouldn't happen, so I don't think it's worth the effort.

2021-05-19 15:58 UTC, TheImpressiveDonut approved these changes

2021-05-19 16:09 UTC, merged