GCalendar interoperability base
Sosol02/sdp pull request #226
Opened 2021-05-15 17:12 UTC by Ef55

Setup the overall logic for the calendar export.
Implement the UI.

2021-05-15 21:33 UTC, Ef55 commented
**Note:** due to the heavy reliance of this code on external UIs (Google SignIn for Android), I sadly cannot get the test coverage higher.

2021-05-16 08:31 UTC, Flechman requested changes
Nice approach to the GCalendar. Since you asked for a method to retrieve all events in the db, I'll wait for you to use the method before approving

2021-05-16 08:31 UTC, Flechman commented on app/build.gradle
> +    implementation 'com.google.android.gms:play-services-auth:19.0.0'
This line is in duplicate

2021-05-16 08:31 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ExportFragment.java
> +        // TODO: ask Remi for a method to get all events (in the future ?)
The method `retrieveAll(Storer<T> storer)` in `(Concrete)Database` retrieves all items stored in the database that belong to the given storer. So you can call `retrieveAll(EventStorer.getInstance()` to get all events in the database.

2021-05-16 08:31 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    public static Event toGCalendarEvents(com.github.onedirection.event.Event event) {
Provide a small `TODO:` ? Minor thing but just to be consistent

2021-05-16 08:31 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        return null;
Same small `TODO:`

2021-05-16 09:31 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ExportFragment.java
> +        // TODO: ask Remi for a method to get all events (in the future ?)
I added a method to _EventQueries_ using the suggested calls to the DB.

2021-05-16 09:32 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    public static Event toGCalendarEvents(com.github.onedirection.event.Event event) {
Added.

2021-05-16 09:32 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        return null;
Added.

2021-05-16 09:32 UTC, Ef55 commented on app/build.gradle
> +    implementation 'com.google.android.gms:play-services-auth:19.0.0'
Duplicate removed.

2021-05-16 09:37 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ExportFragment.java
> +        // TODO: ask Remi for a method to get all events (in the future ?)
Nice

2021-05-16 09:39 UTC, Flechman approved these changes

2021-05-16 10:43 UTC, justagoodguy-omega approved these changes
Seems good

2021-05-16 10:55 UTC, merged