Implement GCalendar events exporter
Sosol02/sdp pull request #228
Opened 2021-05-16 14:05 UTC by Ef55

2021-05-16 15:07 UTC, Ef55 commented
Note that, again, due to the high reliance of this code on systems out of our control, I won't be able to test this code.
(In particular, I couldn't find a way to log Cirrus' emulator into some google account, which would be strict minimum to even consider testing this code).

2021-05-17 09:35 UTC, hugolan approved these changes
good code not much to say here

2021-05-17 09:36 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        List<String> ls = new ArrayList<>();
maybe use a linkedlist here

2021-05-17 20:52 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        List<String> ls = new ArrayList<>();
Why tho ?

2021-05-18 13:53 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        List<String> ls = new ArrayList<>();
little bit faster in this case

2021-05-18 14:12 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        List<String> ls = new ArrayList<>();
![x_doubt](https://user-images.githubusercontent.com/61206225/118666910-d4cbe400-b7f3-11eb-821a-1bb16af1defa.png)

2021-05-19 12:43 UTC, Sosol02 requested changes

2021-05-19 12:43 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        } catch (Exception ignored) { /*Ignore and return empty*/ }
Please Log.d the exception so that we can still have a trace of it

2021-05-19 12:43 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                        assert calendarId != null;
Maybe turn that into Objects.requireNonNull, im not sure assertions are enabled in our builds.

2021-05-19 12:44 UTC, Sosol02 commented
Nice coverage too.

2021-05-19 15:46 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        } catch (Exception ignored) { /*Ignore and return empty*/ }
Done.

2021-05-19 15:46 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                        assert calendarId != null;
It was a leftover; should be gone now.

2021-05-19 15:53 UTC, Sosol02 approved these changes

2021-05-20 21:01 UTC, merged