Event conversion into a Google Calendar Event
Sosol02/sdp pull request #234
Opened 2021-05-17 16:35 UTC by Flechman

2021-05-18 13:33 UTC, hugolan requested changes

2021-05-18 13:33 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    private static final String RFC3339_FORMAT = "yyyy-MM-dd'T'HH:mm:ssXXX";
don't need the seconds right?

2021-05-18 13:33 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                .setSummary(event.getName())
why do you use setSummary instead of setName?

2021-05-18 13:33 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                throw new IllegalArgumentException("Cannot convert a recurring event to a google event if this one is not the first element of the recurrence");
why would you throw an exception in this case? To me if it the second occurrence of a recurring event it should be possible to transform it to a gc recurring as it is itself recurring. But maybe it is to hard to implement.

2021-05-18 13:56 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                .setSummary(event.getName())
Because there's no method called setName hahaha, see the documentation just above that I've shared.
In Google Calendar "Summary" is the equivalent to our "Name"

2021-05-18 16:05 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    private static final String RFC3339_FORMAT = "yyyy-MM-dd'T'HH:mm:ssXXX";
This is a "universal" format that  Google Calendar API uses, so I didn't choose this format. I didn't find any Java methods that use this format so I had to create this string.

2021-05-18 16:09 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                throw new IllegalArgumentException("Cannot convert a recurring event to a google event if this one is not the first element of the recurrence");
We should talk about it in vocal, I'm open to your suggestion. We've already talked about it with Noé and concluded this was the best way to do it.

2021-05-18 18:21 UTC, hugolan approved these changes

2021-05-19 12:38 UTC, Sosol02 approved these changes
Looks okay

2021-05-19 12:38 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            String[] recurr = new String[] {"RRULE:FREQ="+recurrencePeriod+";COUNT="+count};
I don't know if it is normal or not but u have written RRULE, maybe you wanted RULE instead? (I may be completely wrong here)

2021-05-19 13:21 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            String[] recurr = new String[] {"RRULE:FREQ="+recurrencePeriod+";COUNT="+count};
It's indeed RRULE, it's an existing format for the recurrence attributes of Google Calendar Events.

2021-05-19 13:21 UTC, merged