Conversion from Google Calendar Event to Event
Sosol02/sdp pull request #235
Opened 2021-05-18 10:25 UTC by Flechman

2021-05-18 13:21 UTC, hugolan approved these changes
good code nothing much to say here

2021-05-18 13:21 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    private static final String DEFAULT_NAME = "No Name";
why would the default name be no name? maybe put something generic there

2021-05-19 13:47 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    private static final String DEFAULT_NAME = "No Name";
What are your suggestions ? "No name" is good as it gives a hint to the user to give a real event name.

2021-05-19 20:47 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +    private static final String DEFAULT_NAME = "No Name";
I was thinking about something like insert name but ok

2021-05-19 20:48 UTC, hugolan approved these changes

2021-05-20 09:30 UTC, Ef55 requested changes
Just a few details to fix, the overall logic seems good.

I would also strongly encourage you to add a "coherence test", where you convert an event into its GCalendar form, and then convert it back into our Event, to final test equality with the original event.

2021-05-20 09:30 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +        String locationName = (event.getLocation() != null) ? event.getLocation() : "";
I think that an empty string will do just fine.

2021-05-20 09:30 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                    eventCount = Integer.parseInt(info[1]);
- I think a little link to the doc wouldn't hurt (to answer questions like "why 11 ?" or "can info.length > 2 ?");
- I guess that no exception is thrown if multiple rules match, which might not be good.

2021-05-20 09:30 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            }
I think that this map could be put to better use:

- To do _TemporalUnit_ -> _String_, I guess that _.toString()_ might be sufficient;
- The key/values could then be reversed, and you could then simply do `PERIODS.get(periodically).getDuration()`.

2021-05-20 14:42 UTC, Flechman commented
> Just a few details to fix, the overall logic seems good.
> 
> I would also strongly encourage you to add a "coherence test", where you convert an event into its GCalendar form, and then convert it back into our Event, to final test equality with the original event.

My test on the conversion from GCalendar to Event does this check already. I cannot test for equality on events since the conversion changes the ids (because GCalendar id formatting may not be the same as UUID).

2021-05-20 14:49 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +                    eventCount = Integer.parseInt(info[1]);
Done

2021-05-20 15:03 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            }
I don't understand your first point, what is it for ? 
Note that the String is a period such as "DAILY", not a  technical duration format

2021-05-20 15:09 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            }
Second point is done

2021-05-20 15:24 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/GoogleCalendar.java
> +            }
You're indeed right; didn't realized that the strings weren't simply the name of the period.

2021-05-20 15:28 UTC, Ef55 commented
> My test on the conversion from GCalendar to Event does this check already. I cannot test for equality on events since the conversion changes the ids (because GCalendar id formatting may not be the same as UUID).

This might be slightly annoying when we will import events back from GCalendar. 
We will have to discuss that with the «Product owner», and do changes (in a subsequent PR) accordingly.

2021-05-20 15:28 UTC, Ef55 approved these changes

2021-05-20 16:01 UTC, merged