add modifications
Sosol02/sdp pull request #236
Opened 2021-05-18 16:14 UTC by hugolan

2021-05-19 19:12 UTC, hugolan commented
the coverage is low because I wrote code that I will use in the next pr

2021-05-20 08:31 UTC, justagoodguy-omega requested changes

2021-05-20 08:31 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +            eventList.setAdapter(new EventViewerAdapter(events, this));
Here if I understand correctly you are setting a new adapter to update the display of the events which is correct. But a less resource consuming and maybe less error-prone way to do this is to call notifyDataSetChanged() on the adapter. So you can set the adapter once and store it somewhere and then just call myAdapter.notifyDataSetChanged() whenever needed

2021-05-20 08:31 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
>          eventList.setAdapter(new EventViewerAdapter(events, this));
Same here

2021-05-20 08:38 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +            eventList.setAdapter(new EventViewerAdapter(events, this));
yes that be more efficient for updateResults,  but otherwise I need to retrieve the events from the db that were changed and thus create a new one with the new events

2021-05-20 08:39 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +            eventList.setAdapter(new EventViewerAdapter(events, this));
and yes this methods may look useless but in the future I use it in a quite tricky way

2021-05-20 12:03 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +            eventList.setAdapter(new EventViewerAdapter(events, this));
yeah it would require some changes but it may not be important enough to bother

2021-05-20 12:03 UTC, justagoodguy-omega approved these changes

2021-05-20 13:04 UTC, TheImpressiveDonut requested changes
Nice code ! Just a few minor things to see

2021-05-20 13:04 UTC, TheImpressiveDonut commented on app/src/main/res/layout/activity_display_event.xml
> +        android:text="No location precised"
Same you should put this string in strings.xml

2021-05-20 13:04 UTC, TheImpressiveDonut commented on app/src/main/res/layout/recycler_view_event_viewer_adapter.xml
>          android:text="No location precised"
Same

2021-05-20 14:19 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/DisplayEvent.java
> +        if(event.getLocationName() == ""){
yes

2021-05-20 14:19 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/DisplayEvent.java
> +        CompletableFuture<List<Event>> monthEventsFuture = EventQueries.getEventsInTimeframe(Database.getDefaultInstance(),date,date.plusMonths(1));;
nice catch

2021-05-20 14:25 UTC, hugolan commented on app/src/main/res/layout/activity_display_event.xml
> +        android:text="No location precised"
done

2021-05-20 14:26 UTC, hugolan commented on app/src/main/res/layout/activity_display_event.xml
> +        android:text="No location precised"
done

2021-05-20 14:29 UTC, hugolan commented on app/src/main/res/layout/recycler_view_event_viewer_adapter.xml
>          android:text="No location precised"
done

2021-05-20 14:32 UTC, TheImpressiveDonut approved these changes

2021-05-20 14:50 UTC, merged