Implement ui for selecting route to event
Sosol02/sdp pull request #239
Opened 2021-05-19 16:24 UTC by Sosol02

2021-05-20 21:48 UTC, TheImpressiveDonut requested changes
Looks good.

2021-05-20 21:48 UTC, TheImpressiveDonut commented on app/src/androidTest/java/com/github/onedirection/map/MapFragmentTest.java
> +        //assertThat(navigationManager1.getNavigationState(), equalTo(com.mapquest.navigation.NavigationManager.NavigationState.ACTIVE));
Should you leave that?

2021-05-20 21:54 UTC, Sosol02 commented on app/src/androidTest/java/com/github/onedirection/map/MapFragmentTest.java
> +        //assertThat(navigationManager1.getNavigationState(), equalTo(com.mapquest.navigation.NavigationManager.NavigationState.ACTIVE));
It was for the other test that i was about to write, i will remove it ofc.

2021-05-20 22:12 UTC, TheImpressiveDonut approved these changes

2021-05-21 06:30 UTC, justagoodguy-omega approved these changes
All good, and I am very grateful that this was not my task

2021-05-21 06:51 UTC, merged