Order and favorite events view
Sosol02/sdp pull request #262
Opened 2021-05-21 11:02 UTC by hugolan

2021-05-23 20:53 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    }
You can rewrite this as 
```
for (Event e : isOnOrderedView ? orderedEvents : events) { 
     if (favorites.get(e.getId())) listFavorites.add(e);
}
```
Which is less heavy.

2021-05-23 20:53 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    }
Same here

2021-05-23 20:53 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    });
You can use the compareTo(other) of ZonedDateTime (`return l.compareTo(r)`) or
```
return Long.compare(l.getStartTime().toEpochSecond(), r.getStartTime().toEpochSecond());
```
Which is cleaner

2021-05-24 06:41 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    }
yes definitely

2021-05-24 06:41 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    });
yep that's better

2021-05-26 08:08 UTC, Ef55 requested changes
Code-wise, a few little details and some lint warnings to fix and everything should be good.

Functionality-wise, I have a few comments:

- When testing locally, nothing happens when I click on an event, so it seems to me that there is no way to set an event as favorite;
- When clicking the middle buttons, no event is displayed (dunno what it's supposed to do);
- When the list is empty, nothing is displayed (you should write something like "no events").

2021-05-26 08:08 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +        fabOrder.setOnClickListener(fabSortTime());
Those casts are useless.

2021-05-26 08:08 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    }
Could be written:
```suggestion

eventList.setAdapter(new EventViewerAdapter(
  isOnFavoriteView ? favoritesEvents : events, 
  onNoteListener
));
```

2021-05-26 09:29 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +        fabOrder.setOnClickListener(fabSortTime());
yep

2021-05-26 09:30 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                    }
oh yeah this is simpler

2021-05-26 09:34 UTC, hugolan commented
> Code-wise, a few little details and some lint warnings to fix and everything should be good.
> 
> Functionality-wise, I have a few comments:
> 
> * When testing locally, nothing happens when I click on an event, so it seems to me that there is no way to set an event as favorite;
> * When clicking the middle buttons, no event is displayed (dunno what it's supposed to do);
> * When the list is empty, nothing is displayed (you should write something like "no events").

yeah I am going to put the case where there no events
the middle button is supposed to order events by time
it is a long click, but I changed it to just click haven't push it yet

2021-05-26 17:03 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/HomeFragment.java
> +                        //if (l.equals(r)) return 0;
Remove the comment if you don't use it anymore

2021-05-26 17:04 UTC, Flechman approved these changes
The code looks good to me, but you could clean it up even more and refactor the logic in some areas.

2021-05-26 17:09 UTC, hugolan commented
> The code looks good to me, but you could clean it up even more and refactor the logic in some areas.

yeah when I will merge it with the event in the db I'll proceed to a refactor to make it cleaner but not for now

2021-05-26 17:17 UTC, Ef55 approved these changes

2021-05-26 19:44 UTC, merged