Beautify UI of Account + add Import button
Sosol02/sdp pull request #264
Opened 2021-05-22 08:27 UTC by Flechman

2021-05-23 15:01 UTC, hugolan requested changes

2021-05-23 15:01 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ImportFragment.java
> +    private void doSomething(View ignored) {
why do you have this if it does nothing?

2021-05-23 15:15 UTC, Flechman commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ImportFragment.java
> +    private void doSomething(View ignored) {
Because it's @Ef55 ´s task

2021-05-23 16:10 UTC, hugolan commented on app/src/main/java/com/github/onedirection/interoperability/gcalendar/ImportFragment.java
> +    private void doSomething(View ignored) {
ok!

2021-05-23 16:10 UTC, hugolan approved these changes
nice code

2021-05-24 08:02 UTC, Ef55 approved these changes

2021-05-24 08:14 UTC, merged