Feature 'favorite' for Events storable into Database
Sosol02/sdp pull request #274
Opened 2021-05-24 08:29 UTC by Flechman

Adjusted the Event model and the EventStorer such that the event contains a 'isFavorite' attribute and it is storable in the database.

2021-05-27 23:03 UTC, TheImpressiveDonut requested changes
Not much to say, it's mainly a lot of refactor to add the favorite feature to event. It's a nice code, you just forgot two comments at some places.

2021-05-28 07:30 UTC, TheImpressiveDonut approved these changes
Nice

2021-06-03 07:29 UTC, Ef55 requested changes
Everything seems good.
You should just remove the 200+ white lines at the end of `HomeFragment.java`

2021-06-03 09:51 UTC, Ef55 approved these changes

2021-06-03 11:01 UTC, merged