Surprise its a calendar branch again
Sosol02/sdp pull request #275
Opened 2021-05-24 13:12 UTC by justagoodguy-omega

2021-05-26 07:56 UTC, Ef55 requested changes
Seems good.
I just have a few interrogations, and the lint warnings should be fixed.

(Also, happy to see that you saw the light and stopped using the espresso recorder)

2021-05-26 07:56 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/CalendarFragment.java
> +    private final Calendar calendar = Calendar.getInstance(Locale.ENGLISH);
You should most likely get the phone's locale instead.

2021-05-26 07:56 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/EventsListAdapter.java
> +            onDeleteEvent.run();
Nice one :)

2021-05-26 07:56 UTC, Ef55 commented on app/src/main/res/layout/fragment_calendar.xml
> +    android:background="@color/col_on_primary">
Lint warning here.

2021-05-26 11:35 UTC, hugolan requested changes
good code, should be good

2021-05-26 11:35 UTC, hugolan commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/DayEventsListView.java
> +    private void setupEventsListView(View view) {
don't you need to refresh the view after setting up the elements?

2021-05-26 14:50 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/DayEventsListView.java
> +        }
No that is actually taken care of in the adapter, this part is just to specify what should happen in the special case where there are no more events

2021-05-26 14:51 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/EventsListAdapter.java
> +            onDeleteEvent.run();
![image](https://user-images.githubusercontent.com/61226987/119681694-944b1680-be42-11eb-9e3b-9e0ee23af2dd.png)

2021-05-27 08:32 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/calendar/DayEventsListView.java
> +        if(idling != null){
You should require that `idling` is not null in the constructor instead of checking here.

2021-05-27 12:08 UTC, Ef55 approved these changes

2021-05-27 22:46 UTC, merged