General UI fixes
Sosol02/sdp pull request #276
Opened 2021-05-24 14:51 UTC by Flechman

2021-05-24 19:33 UTC, justagoodguy-omega requested changes
A couple lint warnings (I know they were there before but now that you changed the file it's all yours :D

2021-05-24 19:33 UTC, justagoodguy-omega commented on app/src/main/res/layout/activity_display_event.xml
>          android:paddingLeft="4dp"
Lint warning here

2021-05-24 19:33 UTC, justagoodguy-omega commented on app/src/main/res/layout/activity_display_event.xml
> +        android:textSize="32dp"
Here too

2021-05-24 19:33 UTC, justagoodguy-omega commented on app/src/main/res/layout/activity_display_event.xml
>      <ImageButton
And here

2021-05-27 22:40 UTC, TheImpressiveDonut approved these changes
There is only some small changes in xml files so I have nothing to add or comment on. Nice code !

2021-05-27 22:49 UTC, justagoodguy-omega approved these changes

2021-05-28 08:03 UTC, hugolan requested changes

2021-05-28 08:03 UTC, hugolan commented on app/src/main/res/layout/activity_display_event.xml
> +        android:layout_height="65dp"
why did you change this?

2021-05-28 08:06 UTC, Flechman commented on app/src/main/res/layout/activity_display_event.xml
> +        android:layout_height="65dp"
Because it was prettier like this

2021-05-28 08:15 UTC, hugolan approved these changes

2021-06-02 13:20 UTC, merged