Improve events list appearance
Sosol02/sdp pull request #293
Opened 2021-06-01 18:23 UTC by justagoodguy-omega

2021-06-02 08:06 UTC, Ef55 requested changes
LiNt WaRnInGs

2021-06-02 11:35 UTC, justagoodguy-omega commented
> 
> 
> LiNt WaRnInGs

In this case it's

> 
> 
> LiNt WaRnInGs

In this case it's actually a feature not a bug, I just needed a view as padding for aesthetic purposes :)

2021-06-02 11:35 UTC, justagoodguy-omega commented
> 
> 
> LiNt WaRnInGs

In this case it's actually a feature not a bug, I just needed a view as padding for aesthetic purposes :)

2021-06-02 13:23 UTC, hugolan approved these changes
nothing much to say here just ui fixes

2021-06-02 13:23 UTC, hugolan commented on app/src/main/res/layout/day_events_list.xml
>  </LinearLayout>
warning here

2021-06-03 07:19 UTC, Ef55 approved these changes

2021-06-03 12:39 UTC, merged