improve UI and coverage of events in the main menu
Sosol02/sdp pull request #294
Opened 2021-06-02 09:03 UTC by hugolan

2021-06-02 20:05 UTC, Flechman commented on app/src/main/res/drawable/baseline_delete_24.xml
> +</vector>
Unused object, is it normal ?

2021-06-02 20:06 UTC, Flechman commented on app/src/main/res/layout/activity_display_event.xml
> +    <ImageView
Lint warning : put a content description (don't forget to reference the string in strings.xml"

2021-06-02 20:07 UTC, Flechman commented on app/src/main/res/layout/activity_display_event.xml
> +    <ImageView
Same here  (I don't know why it's necessary tho)

2021-06-02 20:07 UTC, Flechman commented on app/src/main/res/layout/activity_display_event.xml
> +
Same :/

2021-06-02 20:08 UTC, Flechman commented on app/src/main/res/layout/recycler_view_event_viewer_adapter.xml
> +    <ImageView
same :(

2021-06-02 20:09 UTC, Flechman commented on app/src/main/res/layout/recycler_view_event_viewer_adapter.xml
> +
Same D:

2021-06-02 20:09 UTC, Flechman reviewed
The UI is pretty

2021-06-02 20:22 UTC, hugolan commented on app/src/main/res/drawable/baseline_delete_24.xml
> +</vector>
nope it should be removed

2021-06-02 20:22 UTC, hugolan commented on app/src/main/res/layout/activity_display_event.xml
> +    <ImageView
ok

2021-06-02 20:40 UTC, Flechman approved these changes
Lint warnings fixed. LGTM now

2021-06-03 07:25 UTC, Ef55 requested changes
I don't have anything to say about the changes in themselves, but you should really fix all those long lasting lint warnings in your classes:
- Add a reason to your `@Ignore`
- Strings displayed to the user should be define in the `strings.xml` file
- You should not store a Fragment as a static field

2021-06-03 09:35 UTC, hugolan commented
> I don't have anything to say about the changes in themselves, but you should **really** fix all those long lasting lint warnings in your classes:
> 
> * Add a reason to your `@Ignore`
> * Strings displayed to the user should be defined in the `strings.xml` file
> * You should not store a Fragment as a static field

ignore is fixed on last week pr just waiting it to be approved 
yeah I should fix the lints
no that that's the only way to do it

2021-06-03 09:53 UTC, Ef55 commented
> > I don't have anything to say about the changes in themselves, but you should **really** fix all those long lasting lint warnings in your classes:
> > 
> > * Add a reason to your `@Ignore`
> > * Strings displayed to the user should be defined in the `strings.xml` file
> > * You should not store a Fragment as a static field
> 
> ignore is fixed on last week pr just waiting it to be approved
> yeah I should fix the lints
> no that that's the only way to do it

- Nice;
- Nice;
- Well, if this is the only way of doing what you are trying to do, then you probably do something you shouldn't.

2021-06-03 20:17 UTC, Ef55 requested changes

2021-06-03 20:17 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/navigation/DisplayEventTest.java
> +    @SuppressWarnings("deprecation")
Dude, really.
It would have been almost quicker to **fix** the lint warning than suppressing it.

2021-06-03 20:17 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/navigation/FavoriteAndSwipeEventTest.java
> +@SuppressWarnings("ALL")
![external-content duckduckgo com](https://user-images.githubusercontent.com/61206225/120706119-ffd35a80-c4b8-11eb-8eff-854a4f9bc4a7.jpeg)

2021-06-03 20:17 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/navigation/HomeTest.java
> +@SuppressWarnings("ALL")
🙃

2021-06-03 20:17 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/navigation/fragment/home/DisplayEvent.java
> +    public static final String EXTRA_MODIFIED = "EVENT__MODIFIED_ID";
```suggestion
    public static final String EXTRA_MODIFIED = "EVENT_MODIFIED_ID";

```

2021-06-03 20:18 UTC, hugolan commented on app/src/androidTest/java/com/github/onedirection/navigation/FavoriteAndSwipeEventTest.java
> +@SuppressWarnings("ALL")
WHYYYYYYYYYYYYYYYY

2021-06-03 20:34 UTC, Ef55 approved these changes

2021-06-04 14:01 UTC, merged