Fix most lint warnings
Sosol02/sdp pull request #300
Opened 2021-06-03 19:20 UTC by Ef55

2021-06-03 20:55 UTC, justagoodguy-omega approved these changes
Thank you for your sacrifice, your country is proud

2021-06-03 21:45 UTC, TheImpressiveDonut requested changes
Nice clean up ! There still some easy fixable lint warnings like hard coded string ! I pointed out on of them which a library warning.

2021-06-03 21:45 UTC, TheImpressiveDonut commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.4.0-beta01'
hmm git hub is telling there is a lint warning here

2021-06-04 13:49 UTC, TheImpressiveDonut approved these changes
So fix my concerns myself ! LOL

2021-06-04 15:23 UTC, merged