Event model
Sosol02/sdp pull request #45
Opened 2021-03-15 08:52 UTC by hugolan

2021-03-15 09:14 UTC, Ef55 requested changes

2021-03-15 09:14 UTC, Ef55 commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.3.0'
Those dependencies shouldn't be added.

2021-03-15 09:14 UTC, Ef55 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".EventCreator" />
Same here: we don't want to use Android Wear.

2021-03-15 09:14 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/Event.java
> +            throw new IllegalArgumentException();
It would be (imo) cleaner to do
```suggestion
        Objects.requireNonNull(name);
        Objects.requireNonNull(location);
        ...
        Objects.requireNonNull(end_time);

```
(Note: we could even write an utility function to write)
```suggestion
        requireNoneNull(name , location, date, start_time, end_time);
```

2021-03-15 09:14 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/Event.java
> +        return new Event(id,new_value,location,date,start_time,end_time);
Shorter
```suggestion
        Objects.requireNonNull(new_value);
        return new_value == this.name ?
            this:
            new Event(id,new_value,location,date,start_time,end_time);

```
I would at least change the Null check (so that CodeClimate stops complaining).
The same applies to all setters.

2021-03-15 09:14 UTC, Ef55 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_world">Hello Square World!</string>
Don't think there is a main2.

2021-03-15 09:14 UTC, Ef55 commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
The main activity was removed in #21

2021-03-15 11:12 UTC, hugolan commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.3.0'
I just delete them?

2021-03-15 15:50 UTC, Ef55 requested changes

2021-03-15 15:50 UTC, Ef55 commented on app/src/androidTest/java/com/github/onedirection/ExampleInstrumentedTest.java
> +}
You shouldn't add this file back.

2021-03-15 15:50 UTC, Ef55 commented on app/src/main/AndroidManifest.xml
> +
This shouldn't be added (again, android wear).

2021-03-15 15:50 UTC, Ef55 commented on app/src/main/java/com/github/onedirection/Event.java
> +    public Event set_name(String new_value){
Java methods' shouldn't use snake_case.
```suggestion
    public Event setSame(String new_value){
```
Same for all setters.

2021-03-15 15:50 UTC, Ef55 commented on app/src/test/java/com/github/onedirection/EventTest.java
> +        String end_time = "end_time";
Would be better to define all those constants as _final static_ attributs.

2021-03-15 17:49 UTC, Ef55 approved these changes

2021-03-16 09:49 UTC, justagoodguy-omega commented on app/src/main/java/com/github/onedirection/Event.java
> +
Should there not be a boolean field for repeat every week and a field for description of the event?

2021-03-16 13:48 UTC, Flechman commented on app/src/main/java/com/github/onedirection/Event.java
> +class Event {
Does not implement Storable

2021-03-16 13:49 UTC, Flechman commented on app/src/main/java/com/github/onedirection/Event.java
> +    final private int id;
id is not an int, should use the Id class

2021-03-16 13:54 UTC, Flechman requested changes
The Event model should implement Storable along with the dedicated methods, and to represent the id it should use the class Id dedicated to unique ids.

2021-03-16 14:06 UTC, Flechman approved these changes

2021-03-16 14:42 UTC, merged