Sol map event details
Sosol02/sdp pull request #92
Opened 2021-04-04 20:37 UTC by Sosol02

2021-04-04 21:26 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +    public void setBottomSheetEvent(Event event){
A little Objects.requireNonNull(event) would be nice

2021-04-04 21:27 UTC, Flechman commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MarkerSymbolManager.java
> +    public MarkerSymbolManager(SymbolManager symbolManager, MapFragment fragment) {
Null checks missing here as well

2021-04-04 21:29 UTC, Flechman approved these changes
Great code Clean code

2021-04-04 21:30 UTC, Sosol02 commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +    public void setBottomSheetEvent(Event event){
The reasoning is that if event is null it crashes with a nullpointerexception anyways, but i can change that.

2021-04-05 08:16 UTC, TheImpressiveDonut requested changes
Nice code

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +            }); // */
Forgot to remove useless commentary

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/java/com/github/onedirection/navigation/fragment/map/MapFragment.java
> +        // */
Should we leave this comment?

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="Start time"
Hardcoded string, put it in strings.xml  it is better

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="Event name"
Hardcoded string, put it in strings.xml it is better

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="End time"
Hardcoded string, put it in strings.xml  it is better

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_map.xml
> +            android:text="Location"
Hardcoded string, put it in strings.xml it is better

2021-04-05 08:16 UTC, TheImpressiveDonut commented on app/src/main/res/layout/fragment_map.xml
> +        android:text="Show collapsed bottom sheet" /-->
Is this useful?

2021-04-05 08:25 UTC, TheImpressiveDonut approved these changes

2021-04-05 08:47 UTC, merged